import type { Metadata } from "next";
import { Inter, Nanum_Myeongjo } from "next/font/google";

import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

import "../globals.css";
import Providers from "../providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const nanum = Nanum_Myeongjo({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-nanum",
});

export const metadata: Metadata = {
  title: "94 Lyceum",
  description: "Generated by Next.js",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <Providers>
        <body
          className={`
          ${inter.variable}
          ${nanum.variable}
          antialiased
        `}
        >
          <NextIntlClientProvider messages={messages}>
            {children}
          </NextIntlClientProvider>
        </body>
      </Providers>
    </html>
  );
}